name: Check Changelog

on:
  push:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - id: check-changelog
        uses: check_changelog/script.sh
        with:
          pr-number: ${{ github.event.pull_request.number }}
          pr-author: ${{ github.event.pull_request.sender }}
